# Generated by Django 5.1.4 on 2025-01-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=50)),
                ('runame', models.CharField(max_length=50)),
                ('remail', models.EmailField(max_length=50)),
                ('rmobile', models.TextField(max_length=10)),
                ('rcrtpass', models.TextField(max_length=10)),
                ('rconpass', models.TextField(max_length=10)),
            ],
        ),
    ]
