# Generated by Django 5.1.4 on 2025-01-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srvc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=80)),
                ('cemail', models.EmailField(max_length=50)),
                ('csub', models.TextField(max_length=200)),
                ('cmsg', models.TextField(max_length=300)),
            ],
        ),
    ]
