# Generated by Django 5.1.4 on 2025-01-22 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srvc', '0003_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
