# Generated by Django 5.1.4 on 2025-01-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srvc', '0006_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
