# Generated by Django 5.1.4 on 2025-01-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srvc', '0007_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbname', models.CharField(max_length=50)),
                ('fbemail', models.EmailField(max_length=80)),
                ('fbnum', models.CharField(max_length=10)),
                ('fbsrv', models.CharField(max_length=200)),
                ('fbmsg', models.TextField(max_length=200)),
            ],
        ),
    ]
