# Generated by Django 5.1.4 on 2025-01-28 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srvc', '0009_export_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='export_product',
        ),
    ]
