# Generated by Django 5.1.4 on 2025-01-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srvc', '0010_delete_export_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='export_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eximg', models.ImageField(upload_to='')),
                ('extitle', models.CharField(max_length=20)),
                ('exdesc', models.TextField(max_length=200)),
            ],
        ),
    ]
