# Generated by Django 5.1.4 on 2025-01-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srvc', '0011_export_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='export_product1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eximg', models.URLField(max_length=500)),
                ('extitle', models.CharField(max_length=20)),
                ('exdesc', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='export_product',
            name='eximg',
            field=models.URLField(max_length=500),
        ),
    ]
