# Generated by Django 5.1.4 on 2025-01-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srvc', '0012_export_product1_alter_export_product_eximg'),
    ]

    operations = [
        migrations.CreateModel(
            name='export_product2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eximg', models.URLField(max_length=500)),
                ('extitle', models.CharField(max_length=50)),
                ('exdesc', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='export_product3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eximg', models.URLField(max_length=500)),
                ('extitle', models.CharField(max_length=50)),
                ('exdesc', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='export_product1',
            name='extitle',
            field=models.CharField(max_length=50),
        ),
    ]
