# Generated by Django 5.1.4 on 2025-01-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srvc', '0013_export_product2_export_product3_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='export_product',
        ),
        migrations.DeleteModel(
            name='export_product1',
        ),
        migrations.DeleteModel(
            name='export_product2',
        ),
        migrations.DeleteModel(
            name='export_product3',
        ),
    ]
