# Generated by Django 5.1.4 on 2025-01-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srvc', '0014_delete_export_product_delete_export_product1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='rconpass',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='rcrtpass',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='rmobile',
            field=models.CharField(max_length=10),
        ),
    ]
