# Generated by Django 5.1.4 on 2025-02-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srvc', '0016_exportform'),
    ]

    operations = [
        migrations.CreateModel(
            name='importform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('Product', models.CharField(max_length=50)),
                ('Quantity', models.CharField(max_length=10)),
                ('State', models.CharField(max_length=10)),
                ('Shipping', models.TextField(max_length=200)),
                ('Payment', models.CharField(max_length=3)),
            ],
        ),
    ]
