# Generated by Django 5.1.4 on 2025-02-01 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srvc', '0017_importform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importform',
            old_name='State',
            new_name='St',
        ),
    ]
