# Generated by Django 5.1.4 on 2025-03-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srvc', '0019_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importform',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
