# Generated by Django 5.1.4 on 2025-03-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srvc', '0020_alter_importform_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportform',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
