# Generated by Django 5.1.4 on 2025-03-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='carrier',
        ),
    ]
