# Generated by Django 5.1.4 on 2025-03-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_remove_productdetail_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='dateshiped',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='estimatedlv',
            field=models.DateField(),
        ),
    ]
