# Generated by Django 5.1.4 on 2025-03-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_alter_productdetail_dateshiped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
