# Generated by Django 5.1.4 on 2025-03-20 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_alter_productdetail_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDetail',
        ),
    ]
