# Generated by Django 5.1.4 on 2025-03-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('track', '0005_delete_productdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=20)),
                ('tracknumber', models.CharField(max_length=9)),
                ('status', models.CharField(max_length=10)),
                ('origin', models.CharField(max_length=10)),
                ('destination', models.CharField(max_length=10)),
                ('estimatedlv', models.DateField()),
                ('dateshiped', models.DateField()),
            ],
        ),
    ]
