# Generated by Django 5.1.4 on 2025-04-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_dyp', '0010_mechanical1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='crudoil1',
        ),
        migrations.DeleteModel(
            name='hardware1',
        ),
        migrations.DeleteModel(
            name='mechanical1',
        ),
        migrations.DeleteModel(
            name='motor1',
        ),
        migrations.DeleteModel(
            name='motor2',
        ),
    ]
